#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run("SECRET=$(mix phx.gen.secret)")
run("export SECRET_KEY_BASE=SECRET")
run("export DATABASE_URL=ecto://postgres:postgres!!!442@127.0.01/database")

run("mix deps.get --only prod")
run("MIX_ENV=prod mix compile")
run("npm run deploy --prefix ./assets")
run("mix phx.digest")
run('PORT=4001 MIX_ENV=prod elixir --erl "-detached" -S mix phx.server')